#include "keydef.h"

keyname_t keynames[] =
{
  { "",          KEY_DUMMY, false, key_aux, 0, 0, 0, 0 },
  //
  // Keyboard keys
  //
  { "a",         KEY_A, true, key_keyboard, 'a', 'A', 0, 0 },
  { "b",         KEY_B, true, key_keyboard, 'b', 'B', 0, 0 },
  { "c",         KEY_C, true, key_keyboard, 'c', 'C', 0, 0 },
  { "d",         KEY_D, true, key_keyboard, 'd', 'D', 0, 0 },
  { "e",         KEY_E, true, key_keyboard, 'e', 'E', 0, 0 },
  { "f",         KEY_F, true, key_keyboard, 'f', 'F', 0, 0 },
  { "g",         KEY_G, true, key_keyboard, 'g', 'G', 0, 0 },
  { "h",         KEY_H, true, key_keyboard, 'h', 'H', 0, 0 },
  { "i",         KEY_I, true, key_keyboard, 'i', 'I', 0, 0 },
  { "j",         KEY_J, true, key_keyboard, 'j', 'J', 0, 0 },
  { "k",         KEY_K, true, key_keyboard, 'k', 'K', 0, 0 },
  { "l",         KEY_L, true, key_keyboard, 'l', 'L', 0, 0 },
  { "m",         KEY_M, true, key_keyboard, 'm', 'M', 0, 0 },
  { "n",         KEY_N, true, key_keyboard, 'n', 'N', 0, 0 },
  { "o",         KEY_O, true, key_keyboard, 'o', 'O', 0, 0 },
  { "p",         KEY_P, true, key_keyboard, 'p', 'P', 0, 0 },
  { "q",         KEY_Q, true, key_keyboard, 'q', 'Q', 0, 0 },
  { "r",         KEY_R, true, key_keyboard, 'r', 'R', 0, 0 },
  { "s",         KEY_S, true, key_keyboard, 's', 'S', 0, 0 },
  { "t",         KEY_T, true, key_keyboard, 't', 'T', 0, 0 },
  { "u",         KEY_U, true, key_keyboard, 'u', 'U', 0, 0 },
  { "v",         KEY_V, true, key_keyboard, 'v', 'V', 0, 0 },
  { "w",         KEY_W, true, key_keyboard, 'w', 'W', 0, 0 },
  { "x",         KEY_X, true, key_keyboard, 'x', 'X', 0, 0 },
  { "y",         KEY_Y, true, key_keyboard, 'y', 'Y', 0, 0 },
  { "z",         KEY_Z, true, key_keyboard, 'z', 'Z', 0, 0 },
  { "0",         KEY_0, true, key_keyboard, '0', ')', 0, 0 },
  { "1",         KEY_1, true, key_keyboard, '1', '!', 0, 0 },
  { "2",         KEY_2, true, key_keyboard, '2', '@', 0, 0 },
  { "3",         KEY_3, true, key_keyboard, '3', '#', 0, 0 },
  { "4",         KEY_4, true, key_keyboard, '4', '$', 0, 0 },
  { "5",         KEY_5, true, key_keyboard, '5', '%', 0, 0 },
  { "6",         KEY_6, true, key_keyboard, '6', '^', 0, 0 },
  { "7",         KEY_7, true, key_keyboard, '7', '&', 0, 0 },
  { "8",         KEY_8, true, key_keyboard, '8', '*', 0, 0 },
  { "9",         KEY_9, true, key_keyboard, '9', '(', 0, 0 },

  { "0_PAD",     KEY_0_PAD, true, key_keyboard, '0', '0', 0, 0 },
  { "1_PAD",     KEY_1_PAD, true, key_keyboard, '1', '1', 0, 0 },
  { "2_PAD",     KEY_2_PAD, true, key_keyboard, '2', '2', 0, 0 },
  { "3_PAD",     KEY_3_PAD, true, key_keyboard, '3', '3', 0, 0 },
  { "4_PAD",     KEY_4_PAD, true, key_keyboard, '4', '4', 0, 0 },
  { "5_PAD",     KEY_5_PAD, true, key_keyboard, '5', '5', 0, 0 },
  { "6_PAD",     KEY_6_PAD, true, key_keyboard, '6', '6', 0, 0 },
  { "7_PAD",     KEY_7_PAD, true, key_keyboard, '7', '7', 0, 0 },
  { "8_PAD",     KEY_8_PAD, true, key_keyboard, '8', '8', 0, 0 },
  { "9_PAD",     KEY_9_PAD, true, key_keyboard, '9', '9', 0, 0 },
  { "F1",        KEY_F1, false, key_keyboard, 0, 0, 0, 0 },
  { "F2",        KEY_F2, false, key_keyboard, 0, 0, 0, 0 },
  { "F3",        KEY_F3, false, key_keyboard, 0, 0, 0, 0 },
  { "F4",        KEY_F4, false, key_keyboard, 0, 0, 0, 0 },
  { "F5",        KEY_F5, false, key_keyboard, 0, 0, 0, 0 },
  { "F6",        KEY_F6, false, key_keyboard, 0, 0, 0, 0 },
  { "F7",        KEY_F7, false, key_keyboard, 0, 0, 0, 0 },
  { "F8",        KEY_F8, false, key_keyboard, 0, 0, 0, 0 },
  { "F9",        KEY_F9, false, key_keyboard, 0, 0, 0, 0 },
  { "F10",       KEY_F10, false, key_keyboard, 0, 0, 0, 0 },
  { "F11",       KEY_F11, false, key_keyboard, 0, 0, 0, 0 },
  { "F12",       KEY_F12, false, key_keyboard, 0, 0, 0, 0 },
  { "ESC",       KEY_ESC, false, key_keyboard, 0, 0, 0, 0 },
  { "`",         KEY_TILDE, true, key_keyboard, '`', '~', 0, 0 },
  { "-",         KEY_MINUS, true, key_keyboard, '-', '_', 0, 0 },
  { "=",         KEY_EQUALS, true, key_keyboard, '=', '+', 0, 0 },
  { "BACKSPACE", KEY_BACKSPACE, false, key_keyboard, 0, 0, 0, 0 },
  { "TAB",       KEY_TAB, false, key_keyboard, 0, 0, 0, 0 },
  { "[",         KEY_OPENBRACE, true, key_keyboard, '[', '{', 0, 0 },
  { "]",         KEY_CLOSEBRACE, true, key_keyboard, ']', '}', 0, 0 },
  { "ENTER",     KEY_ENTER, false, key_keyboard, 0, 0, 0, 0 },
  { ";",         KEY_COLON, true, key_keyboard, ';', ':', 0, 0 },
  { "'",         KEY_QUOTE, true, key_keyboard, '\'', '\"', 0, 0 },
  { "\\",        KEY_BACKSLASH, true, key_keyboard, '\\', '|', 0, 0 },

// WARNING !!!
  { "BACKSLASH2",KEY_BACKSLASH2, false, key_keyboard, 0, 0, 0, 0 },
// WARNING !!!

  { ",",         KEY_COMMA, true, key_keyboard, ',', '<', 0, 0 },
  { ".",         KEY_STOP, true, key_keyboard, '.', '>', 0, 0 },
  { "/",         KEY_SLASH, true, key_keyboard, '/', '?', 0, 0 },
  { " ",         KEY_SPACE, true, key_keyboard, ' ', ' ', 0, 0 },
  { "INS",       KEY_INSERT, false, key_keyboard, 0, 0, 0, 0 },
  { "DEL",       KEY_DEL, false, key_keyboard, 0, 0, 0, 0 },
  { "HOME",      KEY_HOME, false, key_keyboard, 0, 0, 0, 0 },
  { "END",       KEY_END, false, key_keyboard, 0, 0, 0, 0 },
  { "PGUP",      KEY_PGUP, false, key_keyboard, 0, 0, 0, 0 },
  { "PGDN",      KEY_PGDN, false, key_keyboard, 0, 0, 0, 0 },
  { "LEFT",      KEY_LEFT, false, key_keyboard, 0, 0, 0, 0 },
  { "RIGHT",     KEY_RIGHT, false, key_keyboard, 0, 0, 0, 0 },
  { "UP",        KEY_UP, false, key_keyboard, 0, 0, 0, 0 },
  { "DOWN",      KEY_DOWN, false, key_keyboard, 0, 0, 0, 0 },
  { "/_PAD",     KEY_SLASH_PAD, true, key_keyboard, '/', '/', 0, 0 },
  { "*_PAD",     KEY_ASTERISK, true, key_keyboard, '*', '*', 0, 0 },
  { "-_PAD",     KEY_MINUS_PAD, true, key_keyboard, '-', '-', 0, 0 },
  { "+_PAD",     KEY_PLUS_PAD, true, key_keyboard, '+', '+', 0, 0 },
  { "DEL_PAD",   KEY_DEL_PAD, true, key_keyboard, '.', '.', 0, 0 },
  { "ENTER_PAD", KEY_ENTER_PAD, false, key_keyboard, 0, 0, 0, 0 },
  { "PRTSCR",    KEY_PRTSCR, false, key_keyboard, 0, 0, 0, 0 },
  { "PAUSE",     KEY_PAUSE, false, key_keyboard, 0, 0, 0, 0 },

// WARNING !!!
  { "ABNT_C1",   KEY_ABNT_C1, false, key_keyboard, 0, 0, 0, 0 },
  { "YEN",       KEY_YEN, false, key_keyboard, 0, 0, 0, 0 },
  { "KANA",      KEY_KANA, false, key_keyboard, 0, 0, 0, 0 },
  { "CONVERT",   KEY_CONVERT, false, key_keyboard, 0, 0, 0, 0 },
  { "NOCONVERT", KEY_NOCONVERT, false, key_keyboard, 0, 0, 0, 0 },
  { "AT",        KEY_AT, false, key_keyboard, 0, 0, 0, 0 },
  { "CIRCUMFLEX",KEY_CIRCUMFLEX, false, key_keyboard, 0, 0, 0, 0 },
  { "COLON2",    KEY_COLON2, false, key_keyboard, 0, 0, 0, 0 },
  { "KANJI",     KEY_KANJI, false, key_keyboard, 0, 0, 0, 0 },
// WARNING !!!

//  KEY_MODIFIERS

  { "LSHIFT",    KEY_LSHIFT, false, key_keyboard, 0, 0, 0, 0 },
  { "RSHIFT",    KEY_RSHIFT, false, key_keyboard, 0, 0, 0, 0 },
  { "LCONTROL",  KEY_LCONTROL, false, key_keyboard, 0, 0, 0, 0 },
  { "RCONTROL",  KEY_RCONTROL, false, key_keyboard, 0, 0, 0, 0 },
  { "ALT",       KEY_ALT, false, key_keyboard, 0, 0, 0, 0 },
  { "ALTGR",     KEY_ALTGR, false, key_keyboard, 0, 0, 0, 0 },
  { "LWIN",      KEY_LWIN, false, key_keyboard, 0, 0, 0, 0 },
  { "RWIN",      KEY_RWIN, false, key_keyboard, 0, 0, 0, 0 },
  { "MENU",      KEY_MENU, false, key_keyboard, 0, 0, 0, 0 },
  { "SCRLOCK",   KEY_SCRLOCK, false, key_keyboard, 0, 0, 0, 0 },
  { "NUMLOCK",   KEY_NUMLOCK, false, key_keyboard, 0, 0, 0, 0 },
  { "CAPSLOCK",  KEY_CAPSLOCK, false, key_keyboard, 0, 0, 0, 0 },

  //
  // Mouse buttons
  //
  { "MOUSE1",               KEY_MOUSE1, false, key_mouse, 0, 0, 0, 0 },
  { "MOUSE2",               KEY_MOUSE2, false, key_mouse, 0, 0, 0, 0 },
  { "MOUSE3",               KEY_MOUSE3, false, key_mouse, 0, 0, 0, 0 },
  { "MOUSE_WHEEL_UP",       KEY_MOUSE_WHEEL_UP, false, key_mouse, 0, 0, 0, 0 },
  { "MOUSE_WHEEL_DOWN",     KEY_MOUSE_WHEEL_DOWN, false, key_mouse, 0, 0, 0, 0 },

  //
  // Joystick
  //
  { "JOY1_LEFT",            KEY_JOY1_LEFT,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_RIGHT",           KEY_JOY1_RIGHT, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_UP",              KEY_JOY1_UP,    false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_DOWN",            KEY_JOY1_DOWN,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_1",               KEY_JOY1_1, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_2",               KEY_JOY1_2, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_3",               KEY_JOY1_3, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_4",               KEY_JOY1_4, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_5",               KEY_JOY1_5, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_6",               KEY_JOY1_6, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_7",               KEY_JOY1_7, false, key_joystick, 0, 0, 0, 0 },
  { "JOY1_8",               KEY_JOY1_8, false, key_joystick, 0, 0, 0, 0 },

  { "JOY2_LEFT",            KEY_JOY2_LEFT,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_RIGHT",           KEY_JOY2_RIGHT, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_UP",              KEY_JOY2_UP,    false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_DOWN",            KEY_JOY2_DOWN,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_1",               KEY_JOY2_1, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_2",               KEY_JOY2_2, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_3",               KEY_JOY2_3, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_4",               KEY_JOY2_4, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_5",               KEY_JOY2_5, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_6",               KEY_JOY2_6, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_7",               KEY_JOY2_7, false, key_joystick, 0, 0, 0, 0 },
  { "JOY2_8",               KEY_JOY2_8, false, key_joystick, 0, 0, 0, 0 },

  { "JOY3_LEFT",            KEY_JOY3_LEFT,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_RIGHT",           KEY_JOY3_RIGHT, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_UP",              KEY_JOY3_UP,    false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_DOWN",            KEY_JOY3_DOWN,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_1",               KEY_JOY3_1, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_2",               KEY_JOY3_2, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_3",               KEY_JOY3_3, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_4",               KEY_JOY3_4, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_5",               KEY_JOY3_5, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_6",               KEY_JOY3_6, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_7",               KEY_JOY3_7, false, key_joystick, 0, 0, 0, 0 },
  { "JOY3_8",               KEY_JOY3_8, false, key_joystick, 0, 0, 0, 0 },

  { "JOY4_LEFT",            KEY_JOY4_LEFT,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_RIGHT",           KEY_JOY4_RIGHT, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_UP",              KEY_JOY4_UP,    false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_DOWN",            KEY_JOY4_DOWN,  false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_1",               KEY_JOY4_1, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_2",               KEY_JOY4_2, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_3",               KEY_JOY4_3, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_4",               KEY_JOY4_4, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_5",               KEY_JOY4_5, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_6",               KEY_JOY4_6, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_7",               KEY_JOY4_7, false, key_joystick, 0, 0, 0, 0 },
  { "JOY4_8",               KEY_JOY4_8, false, key_joystick, 0, 0, 0, 0 },

  //
  // Reserved
  //
  { "AUX1",                 KEY_AUX1, false, key_aux, 0, 0, 0, 0 },
  { "AUX2",                 KEY_AUX2, false, key_aux, 0, 0, 0, 0 },
  { "AUX3",                 KEY_AUX3, false, key_aux, 0, 0, 0, 0 },
  { "AUX4",                 KEY_AUX4, false, key_aux, 0, 0, 0, 0 },
  { "AUX5",                 KEY_AUX5, false, key_aux, 0, 0, 0, 0 },
  { "AUX6",                 KEY_AUX6, false, key_aux, 0, 0, 0, 0 },
  { "AUX7",                 KEY_AUX7, false, key_aux, 0, 0, 0, 0 },
  { "AUX8",                 KEY_AUX8, false, key_aux, 0, 0, 0, 0 },
  { "AUX9",                 KEY_AUX9, false, key_aux, 0, 0, 0, 0 },
  { "AUX10",                KEY_AUX10, false, key_aux, 0, 0, 0, 0 },
  { "AUX11",                KEY_AUX11, false, key_aux, 0, 0, 0, 0 },
  { "AUX12",                KEY_AUX12, false, key_aux, 0, 0, 0, 0 },
  { "AUX13",                KEY_AUX13, false, key_aux, 0, 0, 0, 0 },
  { "AUX14",                KEY_AUX14, false, key_aux, 0, 0, 0, 0 },
  { "AUX15",                KEY_AUX15, false, key_aux, 0, 0, 0, 0 },
  { "AUX16",                KEY_AUX16, false, key_aux, 0, 0, 0, 0 },
  { "AUX17",                KEY_AUX17, false, key_aux, 0, 0, 0, 0 },
  { "AUX18",                KEY_AUX18, false, key_aux, 0, 0, 0, 0 },
  { "AUX19",                KEY_AUX19, false, key_aux, 0, 0, 0, 0 },
  { "AUX20",                KEY_AUX20, false, key_aux, 0, 0, 0, 0 },
  { "AUX21",                KEY_AUX21, false, key_aux, 0, 0, 0, 0 },
  { "AUX22",                KEY_AUX22, false, key_aux, 0, 0, 0, 0 },
  { "AUX23",                KEY_AUX23, false, key_aux, 0, 0, 0, 0 },
  { "AUX24",                KEY_AUX24, false, key_aux, 0, 0, 0, 0 },
  { "AUX25",                KEY_AUX25, false, key_aux, 0, 0, 0, 0 },
  { "AUX26",                KEY_AUX26, false, key_aux, 0, 0, 0, 0 },
  { "AUX27",                KEY_AUX27, false, key_aux, 0, 0, 0, 0 },
  { "AUX28",                KEY_AUX28, false, key_aux, 0, 0, 0, 0 },
  { "AUX29",                KEY_AUX29, false, key_aux, 0, 0, 0, 0 },
  { "AUX30",                KEY_AUX30, false, key_aux, 0, 0, 0, 0 },
  { "AUX31",                KEY_AUX31, false, key_aux, 0, 0, 0, 0 },
  { "AUX32",                KEY_AUX32, false, key_aux, 0, 0, 0, 0 },

  { NULL,   0, false, key_keyboard, 0, 0, 0, 0 }
};


